### ISSUE TITLE
Unable to show articles in Iceweasel

### ISSUE THREAD

**Issue by KenOokamiHoro** [PoiScript/Solomon#34]
![2017-04-10 10-00-46](https://cloud.githubusercontent.com/assets/26817553/24843417/3f5edff6-1dd5-11e7-8088-9226ec629776.png)

```
10:04:30.853 ERROR Error: Uncaught (in promise): Error: No provider for t!
y@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:2480
k@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:207:275
S@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:207:534
["3j3K"]/</Ii</t.prototype._throwOrNull@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:340:9292
["3j3K"]/</Ii</t.prototype._getByKeyDefault@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:340:9620
["3j3K"]/</Ii</t.prototype._getByKey@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:340:9005
["3j3K"]/</Ii</t.prototype.get@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:340:7413
.kke6/L</<.get@https://poi.works/main.8c78788e71b88a17bee7.bundle.js:1:236504
.kke6/L</e.prototype.getInternal@https://poi.works/main.8c78788e71b88a17bee7.bundle.js:1:244890
["3j3K"]/</eo</t.prototype.get@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:3684
.wJBH/P</<.get@https://poi.works/0.535ddac433887f158322.chunk.js:1:3…
堆栈跟踪：
y@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:2480
l@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:1605
l@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:1291
h/<@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:2119
.ZSR1/</</x</x</t.prototype.invokeTask@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:10552
["3j3K"]/</ao</t.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:7937
.ZSR1/</</x</x</t.prototype.invokeTask@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:10465
.ZSR1/</</x</D</e.prototype.runTask@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:5721
a@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:660
t/this.invoke@https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:11560
 1 vendor.7ac8c1e77af32701b8ee.bundle.js:200:349
	v https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:200:349
	["3j3K"]/</mi</t.prototype.handleError https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:340:221
	["3j3K"]/</bo</e.prototype._bootstrapModuleFactoryWithZone/</<.next https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:12519
	["3j3K"]/</oo</e.prototype.subscribe/i< https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:4842
	.mmVS/c</e.prototype.__tryOrUnsub https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:791:464682
	.mmVS/c</e.prototype.next https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:791:464005
	.mmVS/u</e.prototype._next https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:791:463077
	.mmVS/u</e.prototype.next https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:791:462760
	.EEr4/h</e.prototype.next https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:452:23778
	["3j3K"]/</oo</e.prototype.emit https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:4601
	["3j3K"]/</ao</t.prototype.triggerError https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:8697
	["3j3K"]/</ao</t.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onHandleError https://poi.works/vendor.7ac8c1e77af32701b8ee.bundle.js:354:8297
	.ZSR1/</</x</x</t.prototype.handleError https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:9957
	.ZSR1/</</x</D</e.prototype.runGuarded https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:5320
	a/r https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:760
	a https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:825
	t/this.invoke https://poi.works/polyfills.ad7391608a4787af8d4a.bundle.js:36:11560
```

Support Information in Iceweasel:

> 
> 应用程序概要
> ------
> 
> 名称: Iceweasel
> 版本: 52.0.2
> 版本 ID: 20170402081803
> 用户代理: Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0
> 操作系统: Linux 4.10.8-gnu-1
> 多进程窗口: 0/1（因部分附加组件而禁用）
> 安全模式: false
> 
> 扩展
> --
> 
> 名称: 隐私獾
> 版本: 2017.3.28
> 启用: true
> ID: jid1-MnnxcxisBPnSXQ@jetpack
> 
> 名称: Application Update Service Helper
> 版本: 2.0
> 启用: true
> ID: aushelper@mozilla.org
> 
> 名称: FoxyProxy Basic
> 版本: 3.6.5
> 启用: true
> ID: foxyproxy-basic@eric.h.jung
> 
> 名称: HTTPS Everywhere
> 版本: 5.2.13
> 启用: true
> ID: https-everywhere@eff.org
> 
> 名称: Multi-process staged rollout
> 版本: 1.9
> 启用: true
> ID: e10srollout@mozilla.org
> 
> 名称: notoify
> 版本: 1.0
> 启用: true
> ID: {56ace362-1f95-4252-b94c-667aa681d960}
> 
> 名称: notoify
> 版本: 1.0
> 启用: true
> ID: {0bb81a0c-afc4-4933-a55e-a5ca39d80434}
> 
> 名称: Proxy Switcher
> 版本: 0.1.9
> 启用: true
> ID: jid0-hjBdm7jJii7llLkqacvGnd3gHge@jetpack
> 
> 名称: Site Deployment Checker
> 版本: 1.0
> 启用: true
> ID: deployment-checker@mozilla.org
> 
> 名称: SQLite Manager
> 版本: 0.8.3.1-signed.1-signed
> 启用: true
> ID: SQLiteManager@mrinalkant.blogspot.com
> 
> 名称: Tab Center
> 版本: 1.32.0
> 启用: true
> ID: tabcentertest1@mozilla.com
> 
> 名称: Test Pilot
> 版本: 1.1.2-dev-7338b23
> 启用: true
> ID: @testpilot-addon
> 
> 名称: uBlock Origin
> 版本: 1.11.4
> 启用: true
> ID: uBlock0@raymondhill.net
> 
> 名称: Web Compat
> 版本: 1.0
> 启用: true
> ID: webcompat@mozilla.org
> 
> 图像
> --
> 
> 特性
> 合成: Basic
> 异步平移/缩放: 无
> WebGL 渲染器: Intel Open Source Technology Center -- Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
> WebGL2 渲染器: Intel Open Source Technology Center -- Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
> H264 硬件解码: No
> 音频后端: pulse
> GPU #1
> 活动: 是
> 描述: Intel Open Source Technology Center -- Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
> 供应商 ID: Intel Open Source Technology Center
> 设备 ID: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
> 驱动程序版本: 3.0 Mesa 17.0.2
> 
> 诊断
> AzureCanvasAccelerated: 0
> AzureCanvasBackend: skia
> AzureContentBackend: skia
> AzureFallbackCanvasBackend: none
> CairoUseXRender: 0
> 决策日志
> HW_COMPOSITING:
> blocked by default: Acceleration blocked by platform
> OPENGL_COMPOSITING:
> unavailable by default: Hardware compositing is disabled
> 
> 
> 
> 
> 修改过的重要首选项
> ---------
> 
> accessibility.typeaheadfind.flashBar: 0
> browser.cache.disk.capacity: 358400
> browser.cache.disk.filesystem_reported: 1
> browser.cache.disk.smart_size.first_run: false
> browser.cache.disk.smart_size.use_old_max: false
> browser.cache.frecency_experiment: 2
> browser.download.importedFromSqlite: true
> browser.places.smartBookmarksVersion: 8
> browser.sessionstore.upgradeBackup.latestBuildID: 20170402081803
> browser.startup.homepage_override.buildID: 20170402081803
> browser.startup.homepage_override.mstone: ignore
> browser.tabs.animate: false
> dom.push.userAgentID: cf1531eb80d340ac932a90bb7d4b907d
> extensions.lastAppVersion: 52.0.2
> media.gmp-manager.buildID: 20170402081803
> media.gmp-manager.lastCheck: 1491787898
> media.gmp.storage.version.observed: 1
> network.cookie.prefsMigrated: true
> network.predictor.cleaned-up: true
> places.history.expiration.transient_current_max_pages: 98657
> plugin.disable_full_page_plugin_for_types: application/pdf
> services.sync.declinedEngines:
> services.sync.engine.addons: false
> services.sync.engine.prefs: false
> services.sync.engine.prefs.modified: false
> services.sync.lastPing: 1491736751
> services.sync.lastSync: Mon Apr 10 2017 10:05:41 GMT+0800 (CST)
> services.sync.numClients: 3
> storage.vacuum.last.index: 0
> 
> 重要的已锁定的首选项
> ----------
> 
> browser.startup.homepage_override.mstone: ignore
> 
> Places 数据库
> ----------
> 
> JavaScript
> ----------
> 
> 渐进式垃圾收集: true
> 
> 无障碍环境
> -----
> 
> 已激活: false
> 停用无障碍环境: 0
> 
> 库版本
> ---
> 
> NSPR
> 预期最低版本: 4.13.1
> 目前使用版本: 4.13.1
> 
> NSS
> 预期最低版本: 3.29.3
> 目前使用版本: 3.29.3
> 
> NSSSMIME
> 预期最低版本: 3.29.3
> 目前使用版本: 3.29.3
> 
> NSSSSL
> 预期最低版本: 3.29.3
> 目前使用版本: 3.29.3
> 
> NSSUTIL
> 预期最低版本: 3.29.3
> 目前使用版本: 3.29.3
> 
> 实验性功能
> -----
> 
> 沙盒
> --
> 
> Seccomp-BPF（系统调用过滤）: true
> Seccomp 线程同步: true
> 用户命名空间: false
> 媒体插件沙盒化: true
>

**Comment by PoiScript** [comment]
This problem might be caused by PostService. I'm removing it and using static template instead. Hopefully it can fix this issue.
